language: java
jdk:
- openjdk8

addons:
    sonarcloud:
    organization: "lorenzorossi02"
    token:
        secure: 1bef3a678b243b4563cffe325795cb8fcaf46338
script: 
    - ant build 
    - sonar-scanner
